# Seed add you the ability to populate your db.
# We provide you a basic shell for interaction with the end user.
# So try some code like below:
#
#   name = shell.ask("What's your name?")
#   shell.say name
#
email     = shell.ask "Which email do you want use for logging into admin?"
password  = shell.ask "Tell me the password to use:"

shell.say ""

account = Account.create(:email => email, :name => "Foo", :surname => "Bar", :password => password, :password_confirmation => password, :role => "admin")

if account.valid?
  shell.say "================================================================="
  shell.say "Account has been successfully created, now you can login with:"
  shell.say "================================================================="
  shell.say "   email: #{email}"
  shell.say "   password: #{password}"
  shell.say "================================================================="
else
  shell.say "Sorry but some thing went wrong!"
  shell.say ""
  account.errors.full_messages.each { |m| shell.say "   - #{m}" }
end

shell.say ""


##### Add the Testimonials
testimonials = [
  { author: 'Camelia', content: 'I found the tutorial very useful, with step-by-step explanations. The course material manages to cover a large spectrum of aspects, both architectural and operational, in dense short lessons. <br />The labs provide practical end-to-end examples.', active: true },
  { author: 'Roman', content: 'Dear all, The course is excellent because it saves time from reading big books to learn Hadoop. I prefer agile practice: try to achive small results ASAP. I didn\'t know anything about Hadoop two months ago. <br />But these two months were enough for me to create 7 nodes Hadoop cluster which everyday computes recommendations for our site...', active: true },
  { author: 'Eugeniu', content: 'The course is a great opportunity to get some quick practical experience with Hadoop and its related subprojects. Also the provided vm image could be used for future projects and deepening your understanding of Hadoop framework. Waiting for Hadoop Fundamentals II to be ready :)', active: true },
  { author: 'Joao', content: 'It is the perfect web site to get into new technologies and have a hint of the main and newest projects around big data, open source... The material is really well organized and easy to understand and go through. The labs provide hands-on to the technologies guide you step bu step in the different tasks.', active: true },
  { author: 'Sandeep', content: 'Content is well segregated into different lessons and allowed me to progress smoothly.<br />Flume was something new to me, it was interesting to read about it. The format of a lesson with a transcript, video built on a ppt along with a demo, and labs is well-organized and useful.', active: true },
  { author: 'Andreas', content: 'The course is very interesting, because it explains the components of this new system...The first part was very well detailed, the installation part for the different environments. It was very easy to create the machines in RightScale and register in AWS, or download the application locally...<br />Good work, I will be waiting for the next tutorials.', active: true },
  { author: 'Madhavi', content: 'The lessons in Hadoop Fundamentals I are well organized. The lessons start with an overview of the topic being covered, before going into the finer details. <br />It would however have been helpful if the lessons could cover applications of each of the topics. For example, the scenarios where usage of pig/hive/jaql is well suited. It would also be useful if mapreduce lab sessions could go over the code for wordcount program in detail before running the program. It would also be useful if the lab transcripts could give examples of what parts need to be modified to execute certain sections in the lab tutorial, in the cloud. <br />Overall, the course is well thought out and gives all the details needed to learn the fundamentals of Hadoop.', active: true },
  { author: 'Bhupesh', content: "After much research in the internet I ended up with the tutorial LEARN HADOOP from the BIGDATAUNIVERSITY. In this tutorial the way THEY organized the videos are excellent.<br />It's the very helpfull resource to learn and understand the compents required/involved in the Hadoop ecosystem. I am looking forward to get enrolled for the Hadoop Fundamentals II.<br />Thank you", active: true },
  { author: 'Luca', content: 'Course is nicely split in small parts very well suitable for self peaced learning, even with short timeslot available. <br />I appreciate the availability of Video AND Transcript for each training session. <br />I had on problem with Flume lab run on Virtual Machine: Flume Master was not starting.', active: true },
  { author: 'Arjun', content: 'I must first of all appreciate the wonderfull efforts put in by the team of Big Data University to come up with such a good platform to encourage learning of Hadoop. <br />The material for Hadoop Fundamentals 1 course has been quite informative ... its a great effort and I must appreciate the hard work put in by the experienced and renowned tutors.', active: true },
  { author: 'Bhanu', content: 'Appreciate BigDataUniversity for making this course available for free for general users. Thanks a ton. <br />I am trying to install a simulated environment and would like to do the same with the course...Thank you again for offering this course.', active: true },
  { author: 'Ashish', content: "This is a wonderful startup tutorial, which I discovered very late. It was informative and to the point. I like the short video approach as it helps to completely cover topics without lengthy sittings. <br />It's a perfect way for a quick start. Let me explore the other tutorials. <br />Thanks for al the effort !", active: true },
  { author: 'Aakash', content: 'Very succinct, to the point and perfectly scripted education ! Thanks !', active: true },
  { author: 'Aakash', content: 'The videos are very informative and to the point and also highlight the applications and alternate scenarios very well. This course was an excellent revision of core concepts for me.', active: true },
  { author: 'Abbas', content: 'This course is very informative for Big Data beginners.', active: true },
  { author: 'Abhinandan', content: "This course is very interactive and very informative. It's very useful for beginners.", active: true },
  { author: 'Abhishek', content: 'This course makes BigData understanding very simple..', active: true },
  { author: 'Abhishek', content: 'the course is quite comprehensive and step by step and in a very detailed and proper manner . Thanks to whole BigDatauniversity team for providing such a course for the community...', active: true },
  { author: 'Aditya', content: 'The material was quite great and resourceful. Hadoop proved to be quite an easy task after all...', active: true },
  { author: 'Akhila', content: 'The Course offers  very clear understanding of Hadoop in an easy to understand yet articulate way. <br />Excellent course for a beginner.', active: true },
  { author: 'Akkinepalli', content: 'Hi, The course material is excellent.  Provides a very good introduction to hadoop fundamentals.  This is the best place to kick start your hadoop study.', active: true },
  { author: 'Alex', content: 'it was excelent. Exactly what I need to start to understand big data.', active: true },
  { author: 'Ali', content: 'I would reccomend this course to any one who want to start a career in Hadoop. You can get a solid background in big data with a very short time! Thank you Big Data University...', active: true },
  { author: 'Amar', content: 'very good content, will provide a great insight for any beginner in hadoop technologies', active: true },
  { author: 'Amol', content: 'Very useful course and excellent course contents', active: true },
  { author: 'Andrey', content: 'THanks for the great course!!', active: true },
  { author: 'Anh', content: "I'm very interesting in Hadoop and MapReduce programming, so I strongly apprieciate this course. I gained many useful knowledge when attempt it. Thanks to Big Data University!", active: true },
  { author: 'anil', content: 'Quality of course is awesome !!!', active: true },
  { author: 'Anil', content: 'This course has been a good starter kit for understanding the hadoop fundamentals.', active: true },
  { author: 'Ankush', content: 'Well structured Course, very simply done', active: true },
  { author: 'Anu.L.', content: 'good stuff to learn hadoop', active: true },
  { author: 'Arbind', content: 'Very nicely design all the video are short so it is easy to concentrate , thank you for the wonderful work!!', active: true },
  { author: 'arjun', content: 'Thanks for giving me an oportunity to enroll in to hadoop', active: true },
  { author: 'Arkadiusz', content: 'Really well prepared course: clear presentations, good speakers, everything is profesionally done. Great lessons for beginning with Hadoop tools...', active: true },
  { author: 'Arsalan', content: 'The course material is really helpful to understand the core concepts behind Hadoop...overall training is superb good work.', active: true },
  { author: 'ashok', content: 'Thank you for providing very good preparation stuff.', active: true },
  { author: 'Avais', content: 'Material was superb !!!', active: true },
  { author: 'Avik', content: 'Very good Hand on Tutorial on DB2 and Hadoop....Keep it up', active: true },
  { author: 'Bambang', content: 'Great web training, fast response and complete functionalities to support students to achieve maximum results', active: true },
  { author: 'Bhushan', content: 'Nice Course. It is very effective. <br />I will try to get maximum knowledge from all of them. <br />Nice initiative BigDataUniversity.', active: true },
  { author: 'Bo', content: 'Great forum for learning and nice material. Thanks', active: true },
  { author: 'Bobby', content: 'Good info!! Looking forward to using it in real life scenarios.', active: true },
  { author: 'Boris', content: 'I think it was a very useful overview of the technology related to HADOOP...', active: true },
  { author: 'Brian', content: 'The tutorials, labs and instructions are clear and concise. ...Many thanks for making this available.', active: true },
  { author: 'Bryan', content: 'hello :) this site is great! im currently learning I.T Software Engineering and the courses offered here helps me alot! thanks', active: true },
  { author: 'calvin', content: 'Very good courses...', active: true },
  { author: 'Cassie', content: 'great content', active: true },
  { author: 'Charitha', content: 'Course is really helpful to know the fundamentals of Hadoop. Thanks !!!', active: true },
  { author: 'Cheol', content: 'It was great material to learn BigData - Cheol/Korea', active: true },
  { author: 'CHETENDRA', content: 'first of all thanks to all Bigdatauniversity team for providing such a unique and comprehensive platform for learning HADOOP in a simple and interesting manner. the coursework is prepared in simple, easy to understand but effective and having a proper rhythm  i.e step by step learning its a nice course of bigdatauniversity and I liked a lot being a part of this course', active: true },
  { author: 'Christian', content: 'Great introductory course.', active: true },
  { author: 'CJ', content: 'Good stuff', active: true },
  { author: 'Clinton', content: 'Extremley valuable, helpful and pertainant information.', active: true },
  { author: 'Con', content: 'excellent simple overview of key projects.', active: true },
  { author: 'Conor', content: 'Great introductory class! Thanks so much. Using the cloud for the labs made this course even more interesting.', active: true },
  { author: 'Corinne', content: 'Very good to understand hadoop concepts', active: true },
  { author: 'Dan', content: "This course is awesome, I'm really happy to have found it...", active: true },
  { author: 'Daniel', content: 'Thanks for providing this awesome course. Clear explanations, good examples, good coverage...', active: true },
  { author: 'David', content: 'Very informative course, very well-produced content. Enjoyable and well segmented.', active: true },
  { author: 'Debadeep', content: 'this is a really nice course.thanks', active: true },
  { author: 'Deepak', content: 'It is very well documented course for beginners. Everything is so well explained. <br />I liked the format and the material.', active: true },
  { author: 'Deepak', content: 'The course contents is really excellent and useful.', active: true },
  { author: 'deepak', content: 'The course is well organized and superb...', active: true },
  { author: 'Dmitry', content: 'Thanks! Good piece of work, helps dive into the subject in just one day!', active: true },
  { author: 'Douglas', content: 'I really liked the format, it was very quick to finish and with great info.', active: true },
  { author: 'Dr.', content: 'I found The course very interesting, I looked at the DB2 courses, but my attention Hadoop courses and was quite interesting for the introduction to this world. <br />Thank you very much for your attempts to make us more available knowledge', active: true },
  { author: 'Emilie', content: '"What is Hadoop?" courses are very good since challenges, scenarios and tecnhical aspects are tackled. ...it was an excellent tutorial. Thank you!', active: true },
  { author: 'erik', content: "I appreciate the literal nature of Bradley's hand's on workshops. It goes step by step. Very nice.", active: true },
  { author: 'Eszter', content: 'I like the format very much, especially the lab sections. The fact that the videos are not too long, and the hands-on approach of the labs make this is a very efficient way of learning...', active: true },
  { author: 'Eugene', content: 'This is a really good course to start working with Hadoop technology. Great Job!', active: true },
  { author: 'Filipe', content: 'The course was satisfactory in all respects.', active: true },
  { author: 'Francois', content: 'Good resource for understanding hadoop.', active: true },
  { author: 'Frank', content: 'These courses gave a great overview of the hadoop world and its core applications!', active: true },
  { author: 'Gavin', content: 'Brilliant videos and supporting transcripts. It is a job very well done. Gives a good overview of the topics covered. Theses have to be recommended for anyone who wishes to gain a good understanding.', active: true },
  { author: 'George', content: 'I found the videos to be very helpful in getting to know what/how hadoop and the other technologies work. It is a great introduction to everything... <br />Thanks to everyone involved with putting this togehter I am looking forward to the other courses you have to offer.', active: true },
  { author: 'Govind', content: 'These videos are really very much helpful, I am thankful to this website for providing such opportunity to learn about Big data and Hadoop. Thank you!', active: true },
  { author: 'Goakhan', content: 'That was a comprehensive course, to be completed in a very short time...', active: true },
  { author: 'Graham', content: 'A very helpful review of the basics - makes me want to learn more !', active: true },
  { author: 'Harihar', content: 'all videos are informative and easy to understand about hadoop', active: true },
  { author: 'Himanshu', content: 'Indeed a great initiative taken by Big Data University to provide a clear &amp; straight forward insight into the new technologies that are hitting the IT market. The courses that are included enables a user to get a clear-cut knowledge in a simplified form due to video sessions.This will surely increase the popularity and make everyone comfortable with these evolving technologies.Keep up the good work !!', active: true },
  { author: 'Howard', content: "The Hadoop Fundamentals I course was excellent resource for beginner who want to learn about the technology. The Hadoop's concepts in the videos/Labs were easy to understood the practical use of Hadoop", active: true },
  { author: 'INDRAJEET', content: 'The Hadoop lectures are simple and easy to understand. Well explained...', active: true },
  { author: 'Ionut', content: 'Great courses! They are completing very well the existing books about Hadoop', active: true },
  { author: 'Itajuba', content: "I liked the Hadoop Fundamentals 1 because I've never be in touch with it and the lessons and labs are great to have a initial contact with Hadoop and correlated technologies. <br />The material is not enough to make us experts but the content and examples are simple and easy to understand...Thanks and congratulations for initiative.", active: true },
  { author: 'Ialhan', content: "First of all, thanks for these unique tutorials. Before studying the tutorials, I have no idea what is Hadoop and how I can use. But following the tutorials and doing the great labs instructions, now I can say that I know the things what hadoop's best.", active: true },
  { author: 'Jagdeep', content: 'This in an amazing course and provides a great learning opportunity.', active: true },
  { author: 'janani', content: 'Big data university.com is really great . the courses in the website and online certifications sounds good. if you have upload lab sessions video it wil be great', active: true },
  { author: 'Jennie', content: 'This is a great offering! The accompanying labs are very helpful in reinforcing the educational content on the videos....', active: true },
  { author: 'JeongKwon', content: 'thanks for giving me a chance to learn Hadoop', active: true },
  { author: 'John', content: 'The streaming on your tutorials is pretty fast because @368kbps I can watch your tutorials with no problems at all.', active: true },
  { author: 'John', content: 'Very Good Video presentation; simple to understand.', active: true },
  { author: 'John', content: 'Logical and well structured material. Thank you.', active: true },
  { author: 'Jose', content: 'The hadoop fundamental course is easy to understand and very well paced...', active: true },
  { author: 'JoseLuis', content: 'Thank you for the great insight that has add great knowledge and tear misconceptions on hadoop. Bless you guys!', active: true },
  { author: 'Kamaldeep', content: 'Course material and especially lab sessions are really helpful.I liked tha way the lab sessions are presented.', active: true },
  { author: 'Kapil', content: 'It was nice content and really helpful.', active: true },
  { author: 'Karl', content: 'This course is really helpful, thanks for offering it! ...', active: true },
  { author: 'Kartik', content: "The course material is perfect for the new comers, as well as best for quick revision for the one's who know what is Hadoop.", active: true },
  { author: 'Ken', content: 'Because of a shortage of Big Data learning resources, this is a great resource. <br />It is substantially useful that a completion certificate is provided by this system...', active: true },
  { author: 'Khoa', content: "This should be the best introductory tutorial on Hadoop that I've ever come across.", active: true },
  { author: 'Kuntal', content: 'Big Data University and DB2 University courses are very Good for Beginners like me as well as Campus Student.. It provides a Platform to hunt the Talent of Young Developers.. <br />Thanks to All the members of Big Data University..Looking forward to this type of courses in the near Future as well..', active: true },
  { author: 'Kuntal', content: 'This is the Best e-learning site over the Internet.Hadoop and Db2 courses are very simple , interesting and updated for all kind of user', active: true },
  { author: 'Kuntal', content: 'Very Good Tutorial Series for both beginners and Intermidiate.', active: true },
  { author: 'Kuntal', content: 'This is the BEST online Hands on Training kit of DB2 and Hadoop over the Internet.', active: true },
  { author: 'laiq', content: ' Great course... lookin forward to more...', active: true },
  { author: 'Laura', content: "I'm just starting with Hadoop, the course has really good material both videos and labs...", active: true },
  { author: 'Leonardo', content: "The videos were packed with information. They were clear and concise. You could watch 5 times and still get something you didn't get before...", active: true },
  { author: 'Linda', content: 'The course is quite helpful for getting a quick overview. It is extremely helpful to get a lab environment for some hands on practice. <br />I am eager to see the second part (part II) to be published.', active: true },
  { author: 'Long', content: 'Thank Big Data University for this course. I can understand hadoop umbrella in just 1 day instead of several months.', active: true },
  { author: 'lylian', content: 'Very helpful. <br />Good job', active: true },
  { author: 'Madhuri', content: 'Self Explanatory material provided. <br />Easy to understand.', active: true },
  { author: 'Madhusudhana', content: 'This is an excellant tutorial I have ever seen on Hadoop with good content and excellant lab sessions', active: true },
  { author: 'Mahesh', content: 'Course videos, training material and lab exercises are very detailed and easy to understand.', active: true },
  { author: 'Mahesh', content: '- very helpful course of hadoop<br /> - learned alot of things.<br /> -Thanks', active: true },
  { author: 'Manny', content: 'So far, so good. Material is nicely presented and easy to understand. <br />Looking forward to increased depth in subsequent modules.', active: true },
  { author: 'Manu', content: 'This is very useful tutorial. Thanks a lot.', active: true },
  { author: 'Marcelo', content: 'Hi guys, I really enjoyed this course, it gave me lots of background to understand the basics of Haddop technologies. <br />Thank you!!!', active: true },
  { author: 'Marcin', content: "I think it's a really nice pill of knowledge to a hadoop technology newcomer...", active: true },
  { author: 'Marcio', content: "Congratulations for this course. It's a big opportunity to know the Hadoop and your tools. The video lessons are very good and easy <br />Thanks", active: true },
  { author: 'Mark', content: 'I am grateful that such content exists...', active: true },
  { author: 'Matteo', content: 'I think this course is very useful to understand the basics of Hadoop. <br />The lessons are clear and the concept are explained well, the voice of the speakers are also easy to understand. <br />So my conclusion is: Good.', active: true },
  { author: 'Mauricio', content: 'In general, the course is very friendly and it is very good...', active: true },
  { author: 'Maxinne', content: '...All those learning materials made it easy for me to learn all about Hadoop. All terms are very well explained. Having an option to read or watch a video with all the slides and subscripts kept me focused and made me understand better. Nice website and can be recommended for students like me.', active: true },
  { author: 'Mayur', content: 'This is a pioneer way of coaching people into the brand new space of distributed computing. This is the easiest and most innovative way to ramp up on basic hadoop development. <br />I like the fault tolerance bit and the great part about tools integrated with hadoop like Pig, Hive and JAQL', active: true },
  { author: 'Matea', content: 'The course material is easy to follow and very informative. I installed several Hadoop clusters in my job, but now I know a lot more about what Hadoop can do for me. Thanks guys!', active: true },
  { author: 'Md.', content: 'This course is designed in such a way that makes difficult things easy and convenient to Learn. Thanks to Big Data University For this nice effort', active: true },
  { author: 'meghana', content: 'The videos are very informative and very easy to understand.especially the hands on lab videos.', active: true },
  { author: 'melih', content: 'The course was very useful. I suggest it to all Hadoop beginners.', active: true },
  { author: 'Michael', content: 'This lesson gave me improvements in life. Not just learning the world of hadoop but also the value of time and responsibility.', active: true },
  { author: 'Michael', content: 'Very good training videos. Easy to use and understand. Thanks', active: true },
  { author: 'Michael', content: 'The course is very instructive and very good. Thank you', active: true },
  { author: 'Mike', content: 'Excellent course materials and overall flow. This really helped to solidify some things I have been doing with the system. Thanks.', active: true },
  { author: 'Mike', content: 'A pretty solid, easy to follow introduction to the hadoop family.', active: true },
  { author: 'Mrudula', content: 'Quick and easy course that can be completed in 2 or 3 days. Lab exercies are great too - get a happy feeling that we actually tried something hands-on and got it working!', active: true },
  { author: 'mukund', content: 'A good high level training material which provides an overview of mostly all the components related to Big Data, quite helpful for developers as well as newbies.', active: true },
  { author: 'Muthu', content: 'Video content is short and sweet. Very nicely explained. Looking forward to finish the rest of the course.', active: true },
  { author: 'Nadir', content: '...Thanks for all your help - this course material is very helpful. <br />Best Regards, <br />Nadir Doctor, USA', active: true },
  { author: 'Nanda', content: "Hi, This is really good course... Along with trying Hadoop I also tried using the AWS - Amazon Web Services, and Rightscale for first time. They both are amazing which made me work from anywhere... Once again thank you for the invaluable sessions online.", active: true },
  { author: 'Nikhil', content: 'The course was very helpful in understanding the basics of Hadoop and the different languages that can be used with it.', active: true },
  { author: 'Nong', content: 'I feel this course very useful for Hadoop beginners. It mentioned many aspects of Hadoop fundalmental which are necessary for further studying about Hadoop as well as NoSQL. In my personal case, it help me understand Hadoop very quickly and clearly...Thanks BigDataUniversity about this course.', active: true },
  { author: 'Ohnmar', content: 'I have learned Hadoop Fundamentals I. I took Hadoop and the Amazon Cloud as option lab. I am very interested in this cloud and hadoop. I hope to integrate these knowledge into my current research...', active: true },
  { author: 'Padmanabhan', content: 'Course was well structured and the lab solutions examples were simple and easy to understand...', active: true },
  { author: 'Panuwat', content: 'I think the course is very good for Hadoop beginners. All of the basic concepts of Hadoop in the video can be easily understand. Also, there are labs that help students to understand the practical use of Hadoop commands... I think Big Data University is one of good ways to learn basics of Hadoop.', active: true },
  { author: 'Partha', content: 'This is a very good free of cost tutorial.', active: true },
  { author: 'Pasi', content: 'This is must have course for every data analyst or scientist who wants to be at the top of nod!', active: true },
  { author: 'Peratham', content: 'This course is great!! I can learn Hadoop fundamental easily with step-by-step provided materials and supplied programming environment. Thanks you all!!!', active: true },
  { author: 'Phaneendra', content: 'Excellent matrial to get good understanding of Big Data', active: true },
  { author: 'Pradeep', content: 'Hi Team, <br />Thanks for providing mindblowing tutorials on hadoop and map reduce. hats off to the team who planned and prepared such tutorial. i would suggest to have more such tutorials in future for HBase. also like to see how DB2 can be integrated with hadoop for processing.', active: true },
  { author: 'Pramod', content: 'Really good tutorial... covers almost all the fundamentals.', active: true },
  { author: 'Pranathi', content: 'the turorials are good....descriptive,use simple language and brief !!!!Its fun learning from these less time- consuming tutorials !!!', active: true },
  { author: 'Pranav', content: 'THe Course is Awesome and I really found it interesting. I really thank all the efforts and hard work done by the people who have a maganimous heart to provide this free of cost. Thank you so much.', active: true },
  { author: 'prashant', content: 'Short and upto the point tutorials. It gives enough insights on hadoop and hadoop based projects.', active: true },
  { author: 'Pritiman', content: "Awesome!! The course structure, videos and content is really good from a Beginner's perspective. It covers all the basic concepts in a organized and elegant fashion!! <br />I would recommend and suggest Hadoop Beginners to try this Intoductory course. <br />-Pritiman", active: true },
  { author: 'Rakhi', content: 'The course is very informative and the duration of the videos of this course is concise and easy to absorb. Gives a good insight on Hadoop.', active: true },
  { author: 'Raksha', content: 'I am enlightened by the course and got to know so many concepts about Big Data.', active: true },
  { author: 'Randy', content: 'Very informative. Gives me an understanding of the Hadoop technology.', active: true },
  { author: 'Ranjan', content: 'Excellent fundamentals on Bigdata and Hadoop. I was wondering where to start and stumbled upon your site. Now I know a great deal about Bigdata and Hadoop. I have even downloaded the BigInsights VMWare and started playing with it. Thank you so much for this courseware.', active: true },
  { author: 'ratan', content: "It is a big step for big data learner. Currently I am working at hadoop technologies. It's materials are limited. So, if we have site which provide people to learn big data technologies I think it is really a big step by Big Data university <br />Thanks and Regards, <br />Ratan", active: true },
  { author: 'renato', content: 'Thanks, a very good course to achieve the hadoop basic knowledge.', active: true },
  { author: 'Ricardo', content: 'The course is very interesting, specially for beginners who want learn about big data technologies. Great initiative. Congratulations to the team that created this course.', active: true },
  { author: 'Ritesh', content: 'The course content seems to be pretty exhaustive and excellent.', active: true },
  { author: 'Robert', content: 'Thank you for the course, I hear a lot about BigInsights and wanted a basic understanding. The lectures were clear and easy to follow...', active: true },
  { author: 'Romeo', content: 'The course was very insightful, straight-forward and a great T3 resource. As a Trainer, your notes at the end of each slide, helps to explain the concepts more easily.', active: true },
  { author: 'Ruslan', content: "Hello, <br />First of all thank you for great course, it was really interesting and useful. Hadoop wasn't something new for me, but Big Insights was and now I can easily install and use hadoop, pig, hive, jaql and flume. It is a good bootstrap for people who are looking to start with big data... One more time thank you very much, everything was good and interesting! Will see how's good I got this knowledge. I do hope all yours dreams and ideas will come true.", active: true },
  { author: 'sadanand', content: "This was my first shot at learning Hadoop and feel empowered already. Thank you for great insights and demo's. Truly wonderful stuff.", active: true },
  { author: 'Sagar', content: 'this is really good and great material. and one of the most great material for learning hadoop in shorttime period. thanks to all teamember ..', active: true },
  { author: 'Sai', content: 'Hadoop Tutorial was very helpful..especially the Transcript provided by the videos is very helpful!!Great going!!', active: true },
  { author: 'Sameer', content: 'This was an excellent course. Looking forward to a course which is more advanced which show how to setup a fully clustered hadoop instance on Amazon Cloud.', active: true },
  { author: 'Santosh', content: 'Excellent videos and interactive mode of online teaching. Instructors are very informed and clear while communicating.', active: true },
  { author: 'Sercan', content: 'I did enjoy my journey on online lesson: "Hadoop Fundamentals I". I was actually trying to understand such a parallelization framework to enhance my code used for studies on data mining techniques, and Hadoop, I guess, is the answer for that. I appreciate the efforts on making the course materials...', active: true },
  { author: 'Sevinthi', content: "BigDataUniversity is right place to learn the basic's of Big Data. <br />Big Data University is providing good basic course meterial for the hadoop. Thanks", active: true },
  { author: 'shashidhar', content: 'Thank You alot for providing such a great platform to learn innovative technology, so easily in a simple way.', active: true },
  { author: 'SHAZIYA', content: 'Thanks. <br />Good videos for easy learning.', active: true },
  { author: 'Shilpa', content: 'Very nice course to learn the fundamentals for a beginner.', active: true },
  { author: 'Shobha', content: 'Great', active: true },
  { author: 'Shrihari', content: 'Good Course, I must say and thank. Well organized and it gives good start with overall understanding for the beginers.', active: true },
  { author: 'Siddharth', content: 'The course is just awesome', active: true },
  { author: 'Siraj', content: 'Hadoop Fundemanetals I was great, I learned a lot in a clear concise way. The videos, slides, labs were all great. The material presented quickly answered my qustions to Hadoop and big data. BDU did an excellent job! I want to learn more from BDU classes.', active: true },
  { author: 'Siva', content: 'The course structure is well organized. We have the facility to review and also it provide pragmatic approach by providing necessary methods with the tools as well. Good.', active: true },
  { author: 'Sivasubramaniam', content: 'This is very Good, I was clueless about hadoop before, now i am able to understand it.. :)', active: true },
  { author: 'Smita', content: 'Very good presentation and reading material.Excellent documentation ad videos.', active: true },
  { author: 'Smruti', content: 'The videos were interactive and self learning.', active: true },
  { author: 'Stephen', content: 'Very nice hands-on walkthrough of big data technologies. Much more valuable that the time spent on much too high-level whitepapers and big data presentations.', active: true },
  { author: 'Sujay', content: 'thanks for the very comprehensive course!', active: true },
  { author: 'sulekha', content: 'the tutorial is awesome.provides very good information.', active: true },
  { author: 'Szegedi', content: 'Good introductory course, focusing on the most important aspects of Hadoop.', active: true },
  { author: 'Tamilvani', content: 'BigDataUniversity is very useful to learn the basic knowledge of BigData on Cloud.', active: true },
  { author: 'Tapan', content: 'Nice courses for self-learning.', active: true },
  { author: 'Tarakeswara', content: 'Thanks for providing valuable tutorials.', active: true },
  { author: 'Tejas', content: '- Course had good videos for a person like me who has no prior knowledge of Hadoop. - Material was short and comprehensive.', active: true },
  { author: 'Theofilos', content: 'Great 101 course to get started using Hadoop, with well prepared hands-on labs, and with material fair spread in theory and practical lessons. I used a self prepared environment with built from source hadoop, zookeeper, hive, flume ports, but there were no problem at all following the biginsights commands. Thank you for the good work on building such a good structured hadoop course Big Data University.', active: true },
  { author: 'Thomas', content: "In general this course gives an very good overview about Hadoop and it's core components...", active: true },
  { author: 'Thomas', content: 'it was cool', active: true },
  { author: 'Tim', content: 'Course was relevant and helpful in understanding some basics about BigInsights Hadoop. I would recommend to anyone needing basic start up skills. I found the videos very well done and communicated subject matter clearly and concisely.', active: true },
  { author: 'Tom', content: 'great stuff', active: true },
  { author: 'Umar', content: 'As a developer, i was only involve in PHP, HTML,.NET, SQL and don\'t know these world leading technology which are being used by Internet Giants. After Hadoop course, i am able to know. what is it and whats the use as a developer in Applications. All the Course work is great. The most best thing i like is "Transcripts" of Lectures...', active: true },
  { author: 'Varad', content: 'Hadoop is the Technology that will shape the future of large scale computation and we should expect more and more technologies revolving around hadoop. Its nice to see that there is someone who has taken it on themselves to teach and enlighten the students about what hadoop and mapreduce is ... and what to expect from the future ...The lectures were great .. and the profs were expert oraters and speakers ...Thank You bigdatauniversity.com for starting such a venture .. and making it possible for even a simple college student to learn the state of the art technology ... <br />Thanks Again, <br />Varad', active: true },
  { author: 'Varad', content: 'Big Data University is the only one-stop learning center for high-end Technologies. Hadoop, Pig, Jaql .. These things cannot be taught by anyone without the working knowledge of them. Bigdata Uni. gives opportunity to learn from the industry experts in the field of data management and information retrieval. <br />Thanks BigDataUni...', active: true },
  { author: 'Vijayakumar', content: "Name : Vijayakumar Ramdoss <br />Country : India <br /> This online course gave me a  vey big chance to enlighten myself again, to feel myself as a student  hunger for the 'knowledge', challenged me to rediscover brand new  things, also the things I have already know but not eager to practise. I  think BigDataUniversity is a very good helper and I want  to thank to each person who organized and worked for this course", active: true },
  { author: 'Vikram', content: 'Very nice course content.Useful and informative', active: true },
  { author: 'vishwanath', content: 'good initiative for bigData. keep up the courses industry updates', active: true },
  { author: 'Wannapon', content: 'I think the resources that provided within Big Data University are really valuable for those people who what to study them. I love the way you provide everything right there for everyone to come access it easily. Although most courses are available in English, you still think about those people who are not good in English. You provides sub-titled for every single videos that make me appreciated about it. I also like the way you put it as many short clips instead of one long clip. That makes people feel better. Keep doing you job with more courses! Thx. :)', active: true },
  { author: 'Weiwei', content: 'This is the best course I have taken up to now.', active: true },
  { author: 'Welch', content: 'very useful fundamental course about hadoop. Thanks', active: true },
  { author: 'Yalcinkaya', content: 'I did not know anything about Hadoop before I took this lessons. Videos are great and not boring. Thank you for this resources...', active: true },
  { author: 'Yogesh', content: 'The course content is good and gives the fundamental introduction to hadoop. The content is good enough to understand the use of Pig, Hive and Jaql languages to work on hadoop clusters.', active: true },
  { author: 'yuvraj', content: 'This is really good site i ever observe .As i was new to the this technology Big Data University helps me a lot to understand and cleared each and every concepts  thank you team, really great efforts...', active: true },
  { author: 'Zach', content: "I really like the format for videos. Short, concise and to the point. Can't think of a better introductory course than what is offered by Big Data University for BigInsights!", active: true },
  { author: 'Alexander', content: 'Thanks very much for the course - very clear, and gets you off to a flying start with account creation and other necessities.', active: true },
  { author: 'Camelia', content: "It's a great course , very instructive.", active: true },
  { author: 'Earth', content: 'The course is really nice and up to date...the course is awesome. :)', active: true },
  { author: 'eswar', content: 'The course is very helpful.', active: true },
  { author: 'Heitor', content: 'It is just an amazing open-mind opportunity to new trends. The course modules are simple, short, straight forward and an outstanding opportunity to start learning hadoop. Great!', active: true },
  { author: 'Khoa', content: 'Great course on integrating the Hadoop and Amazon Web Services', active: true },
  { author: 'Leon', content: 'This course was very informative. I appreciate the fact that this course is free, but yet so enlightening.', active: true },
  { author: 'Ohnmar', content: 'I have taken a course "Hadoop &amp; Amazon Cloud". It is effective to the learners who want to explore into new technology for their own purposes. Not only it is very nice course structure with  the content, design and methods, but also it is easy to understand and apply in real world implementation. Thank you for your offering for OPEN and FREE to learn for all. ', active: true },
  { author: 'Pranathi', content: 'The simple overview of amazon cloud and rightscale is good !!', active: true },
  { author: 'sadanand', content: 'Simple but powerful and informative modules. Great way to start learning..', active: true },
  { author: 'Samprita', content: 'I liked this course very much. The information about Amazon AWS and right scale is very useful. I looking forward for more of these courses from Big data University', active: true },
  { author: 'Siraj', content: 'Awesome, I love it!', active: true },
  { author: 'Bambang', content: 'In this letter, i will give a bit comments and big applauses to the Big Data University and DB2 teams for providing me this incredible resources ! <br />The contents are uptodate, timings for video are just right and the certificate features are just awesome. <br />Two Thumbs Up! <br />Bambang Liem', active: true },
  { author: 'Dawn', content: 'Great introduction to the Smart Cloud. Nice to be able to view the videos to gain an understanding without having to spend any money yet!', active: true },
  { author: 'Gourav', content: 'Course content is very good.', active: true },
  { author: 'John', content: 'Effective overview of IBM Cloud offering for Hadoop.', active: true },
  { author: 'mukund', content: 'Very informative course for Hadoop on IBM SmartCloud. Provides details regarding cloud computing, ease of use of IBM SmartCloud Enterprise and clear instructions on how to get started with BigInsights on cloud.', active: true },
  { author: 'Pedro', content: 'Great course and great site.', active: true },
  { author: 'prakash', content: 'Thanks for providing the brief course.This is a very good starting point to Learn Hadoop on IBM Smart Cloud.', active: true },
  { author: 'Pritiman', content: 'Nice Artifacts. Very neatly organized and very helpful for newbies :-)', active: true },
  { author: 'Siraj', content: 'Good overview of IBM Smart Cloud and Hadoop Cluster creation.', active: true },
  { author: 'Vijayender', content: 'This is an awesome course on introduction to Cloud computing and Hadoop. Please keep more information flowing. Thank you.', active: true },
  { author: 'Vipin', content: 'This Course is really worth and very knowledgeable. <br />Thanks', active: true },
  { author: 'Ali', content: 'For anyone interested in the big data buzz , this course will be your " Big Picture of Big Data " ..', active: true },
  { author: 'Andreas', content: 'This course is very interesting, because it explain real cases where big data should be analyzed...This course gave me an idea of how to use big data, not just with Twitter, but with other data sources.', active: true },
  { author: 'Anil', content: 'The content has been extremely good. Use cases on multiple verticals like Banking etc. will enrich this further. Certification on this will definitely be a value add.', active: true },
  { author: 'aravind', content: 'Good introductory course. Lot of focus on what BigInsights platform can do and the usecases. Very helpful...', active: true },
  { author: 'Axel', content: 'Good overview of what you can do with BigInsights - thank you', active: true },
  { author: 'bernie', content: 'Overall, a great set of tutorials. <br />The last 2 videos are too short. But they are good to be used as short case studies to weave into a larger story.', active: true },
  { author: 'C.', content: 'BD100EN was a great introduction into Big Data.', active: true },
  { author: 'Chengmin', content: 'This is a nice overview of bigdata, content analytics and associated technology...', active: true },
  { author: 'Dawn', content: 'Interesting demos.', active: true },
  { author: 'Earth', content: 'The course is great! Hope to see other courses like this. :) Thank you. ;)', active: true },
  { author: 'Edgar', content: 'Very helpful course. It\'s amazing how information (data) could provide "knowledge" using the correct tools.', active: true },
  { author: 'Fan', content: 'This course is a good, comprehensive into to BigInsight.  I appreciate the work your team putting together.', active: true },
  { author: 'Florin', content: 'Excelent resource. Gives a short, but clear overview of the hadoop ecosystem...', active: true },
  { author: 'Harman', content: "Very impressive - showing the power of Hadoop, BigInsights and Streaming Data analysis for Big Data. I was particularly enthusiastic about the videos from David Barnes. The demo was clear, consice and had the actual software running to show the power of BigInsights and BigSheets. <br />I also enjoyed Tina Chen's video, but I wish there was an actual demo of it in action. Overall, great job - I am definitely interested in learning more about BigData and feel it is big part of companies in the future, and see future in it for myself as well.", active: true },
  { author: 'J', content: 'This has been a very useful course to follow - a good introduction tothe concepts and ideas of Big Data. I am now eager to follow the nextset of courses.', active: true },
  { author: 'Jack', content: 'The email demo was excellent in its detail. Tina did a great job.', active: true },
  { author: 'Jagdeep', content: 'The course is very well designed ...', active: true },
  { author: 'Mike', content: "This course is excellent, which give a whole picture of Big Data and IBM's solution on it and also some detailed processes that shows how to find values from real world.", active: true },
  { author: 'Norbert', content: 'Good introduction to uses of hadoop and biginsights. Videos are of high quality.  Thanks.', active: true },
  { author: 'Padmanabhan', content: 'The audio visuals neatly explain the concepts  with illustrations and makes it easy for beginners to understand what  Big Data and Big Insights means to the customers.', active: true },
  { author: 'Paul', content: 'Good introduction on the broad applicability of analytics on BigData.', active: true },
  { author: 'Ron', content: 'I found the course to be very informative... It was great to see the tools in action.', active: true },
  { author: 'sadanand', content: "The demo's are very useful in understanding some of the practical use of BigInsights and whole nine yards. Great way to start getting into deeper knowledge. I wished the sessions were longer!", active: true },
  { author: 'Serge', content: 'The course helps to understand what Big Data is and is not. The use cases are clearly explained and it gives an idea of the skills that are needed to build a Big Data capability.', active: true },
  { author: 'Simanchala', content: 'Thank you very much for presenting such valuable information here.It really helps me in understanding BIGDATA.', active: true },
  { author: 'Smita', content: 'very nice explaination related to big data. <br />The free ebook is very good and explains the things nicely. <br />Nice documentaiton of the hadoop and big insights.', active: true },
  { author: 'Subrat', content: 'The site is very informative.The videos are like classroom training.', active: true },
  { author: 'sunil', content: 'excellent videos, enjoyed the "Why Big Data" video. Showed my boss...', active: true },
  { author: 'Walter', content: 'Good introduction to some of the Big Data concepts. Nice examples, with some very good demonstrations of IBM tools and techniques.', active: true },
  { author: 'Paul', content: 'Very good introductory course [on Text Analytics]. I followed along the lessons in IBM Data Studio. That was really practical.', active: true },
  { author: 'Stefan', content: 'FANTASTIC COURSE!  I came in with zero knowledge on AQL some regex knowledge. After this course I can already start thinking about how to do quite sophisticated text annotators! The Regex tutorial at the end is the best I have come across on the web yet - and I have looked a fair bit! Will definitely recommend this to any people interested in Regex and AQL.', active: true },
  { author: 'Cristian', content: "I am familiar with dbs, as I interacted before in my work (quality assurance), but I have to learn more, now, with my new project which consists of testing db services. <br />I like this course because it's very well structured. I had all this material for reading, but as other times when I had to self educate myself, I didn't know where to start... and I often found myself starting with more books at a time and never got to finish them. This is why I was saying that is very well structured. First watch the videos for an overview, then read chapter X from book A, and chapter x, y, z from book B. Then summarize with exercises. So far, I can't criticize anything... Didn't find anything I disliked about the course...Thank you for a new learning experience!", active: true },
  { author: 'Dmitry', content: "Hello, I have just completed with final exams at SQL Fundamentals course and waiting for results...Thanks a lot for this resource!!!!Videos are short, but very informative! <br />Specially thanks for free books for our campus! <br />I will glad to take part in another BigDataUniversity courses (I hope, that I've graduated SQL basic course;) )I suppose it would be DB2 and Data Studio Essential Trainings, while I hope to get IBM DB2 Certificate in future...", active: true },
  { author: 'Dwight', content: 'Excellent step by step instructions. Great examples. Well laid out videos for the novice.', active: true },
  { author: 'Earth', content: "This is a wonderful course... thanks! :)", active: true },
  { author: 'Janeth', content: "In my opinion I believe this course is very well organized structure, the exercise it's simple to do and understand, the content is very comprehensive and dealt with the fundamental concepts for the creation of databases, which are of vital importance. I have no more than thank you for the opportunity to learn for free.", active: true },
  { author: 'Kirk', content: 'Really enjoyed this course, this course helped me alot to gain a better knowledge in particular with joins etc.', active: true },
  { author: 'Natalia', content: 'I am a new in the on-line studying but I really enjoyed to do so with BigDataUniversity. This is a great opportunity to gain and improve your skills from any place or in any time. <br />Thanks for all the materials you provided for the cours. It was so easy to understand and practice. <br />You are doing a great job. <br />Never give up!', active: true },
  { author: 'Nutchapon', content: 'This course is great about basic SQL for beginner. For my opinion, it is short as well as how good explaination. Cheer up !', active: true },
  { author: 'Ramki', content: 'This course was really awesome. The way they have given the course was really useful ( The examples given were real time examples). step by step explanation was the best part. Thanks for giving such a course and materials. thanks a lot', active: true },
  { author: 'Weslei', content: 'Thnaks for all, the course was excelent.', active: true },
  { author: 'Anupurba', content: 'The course was very descriptive and easy to understand.Videos are very good. I have enjoyed and learnt a lot...', active: true },
  { author: 'Daniel', content: 'I really appreciate the quality of the material and the content of this course!! <br />Congrats to all BigDatauniversity.com team!', active: true },
  { author: 'Kirk', content: 'I thought the course was very good and very easy to follow, I also thought the videos were very helpful...', active: true },
  { author: 'Cristian', content: 'This is a very well put together course for IBM DataStudio for beginners which covers some basics of the Eclipse platform also. <br />Thanks for another great course!', active: true }
]

pbar = ProgressBar.create( title: 'Seed testimonials', total: testimonials.count, format: '%a |%b>>%i| %p%% %t [%c/%C done]' )
testimonials.each do |t|
  Testimonial.find_or_create_by_content( t )
  pbar.increment
end

##### Add the news, aka the slides in the carousel
news = [
  { position: 1, img_url: 'http://placehold.it/1200x480&text=Demystifying+Big+Data+in+Government', title: 'Demystifying Big Data in Government', description: 'Demystifying Big Data in Government', url: 'http://www.ibm.com/common/ssi/cgi-bin/ssialias?subtype=WH&infotype=SA&appname=SWGE_IM_DD_USEN&htmlfid=IML14336USEN&attachment=IML14336USEN.PDF', active: false },
  { position: 2, img_url: '/img/news/slide-power-of-big-data.jpg', title: 'Harness the Power of Big Data', description: 'Sign up now for a chance to receive a free copy', url: 'http://bigdatauniversity.com/courses/course/view.php?id=301', active: true },
  { position: 3, img_url: '/img/news/slide-hadoop-for-dummies.jpg', title: 'Hadoop for Dummies', description: 'Discover Effective Data Solutions for Your Organization', url: 'http://bigdatauniversity.com/courses/course/view.php?id=301', active: true },
  { position: 4, img_url: '/img/news/slide-bdu-facebook-community.jpg', title: 'Join our community', description: 'Join our growing Facebook community today!', url: 'https://www.facebook.com/bigdatauniversity', active: true }
]

pbar = ProgressBar.create( title: 'Seed news', total: news.count, format: '%a |%b>>%i| %p%% %t [%c/%C done]' )
news.each do |n|
  News.find_or_create_by_title( n )
  pbar.increment
end
